# Generated by Django 5.0.14 on 2025-09-22 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('homework', '作业题解答'), ('explanation', '代码解释'), ('chat', '普通聊天')], max_length=20, verbose_name='请求类型')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI回应')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '请求记录',
                'verbose_name_plural': '请求记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('endpoint', models.CharField(blank=True, max_length=100)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': '性能指标',
                'verbose_name_plural': '性能指标',
                'db_table': 'performance_metrics',
                'indexes': [models.Index(fields=['timestamp', 'metric_type'], name='performance_timesta_f88927_idx'), models.Index(fields=['endpoint', 'timestamp'], name='performance_endpoin_9ae185_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('code_content', models.TextField(verbose_name='代码内容')),
                ('method_description', models.TextField(blank=True, verbose_name='方法说明')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='rcode_helper.requestlog', verbose_name='关联请求')),
            ],
            options={
                'verbose_name': 'R代码解决方案',
                'verbose_name_plural': 'R代码解决方案',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(max_length=50)),
                ('page_url', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': '用户行为分析',
                'verbose_name_plural': '用户行为分析',
                'db_table': 'user_analytics',
                'indexes': [models.Index(fields=['timestamp', 'action_type'], name='user_analyt_timesta_5ef4e9_idx'), models.Index(fields=['session_id', 'timestamp'], name='user_analyt_session_ab9810_idx')],
            },
        ),
    ]
